# Generated by Django 4.2 on 2023-04-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.BigIntegerField(),
        ),
    ]
